apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 111868661773.dkr.ecr.us-west-1.amazonaws.com/myapp-repo
  newName: 111868661773.dkr.ecr.us-west-1.amazonaws.com/myapp-repo
  newTag: d9b5eba4
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml
- myapp-service-patch.yaml
